### PR TITLE
add more languages to calendar

### PR DESCRIPTION
**Pull request by sadeghipour**

### CODE REVIEW

**Comment by maggialejandro** [comment]
Hi, thanks for your PR!
I'm seeing that the months are always shown as January
simulator screen shot - iphone 5s - 2018-12-21 at 12 48 48

Could you please fix that and run prettier before so I could merge this?
Thanks!

**Comment by sadeghipour** [comment]
I tested it and working when I pass locale="tr" "ar" "fa" and "de".
unadjustednonraw_thumb_2

**Comment by sadeghipour** [comment]
I guess that I find out why your phone shows just Jan.

The problem is that **toLocaleDateString** is not working stable in React Native, unfortunately.

I will try to fix it with moment or something else.

**Comment by maggialejandro** [comment]
I'm closing this due to inactivity, feel free to send a new PR :rocket:

**Pull request closed without merging**
